# Generated by Django 5.1.1 on 2024-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulatant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='time_slot',
        ),
    ]
